version: '3'
services:

## Router
  routerF01:
    image: mongo:5.0.1
    container_name: router-F01
    command: mongos --port 27017 --configdb rs-config-Fserver/configsvrF01:27017,configsvrF02:27017,configsvrF03:27017 --bind_ip_all
    ports:
      - 27117:27017
    networks: 
      - shardingf
    restart: always
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_routerF01_db:/data/db
      - mongodb_cluster_routerF01_config:/data/configdb
  routerF02:
    image: mongo:5.0.1
    container_name: router-F02
    command: mongos --port 27017 --configdb rs-config-Fserver/configsvrF01:27017,configsvrF02:27017,configsvrF03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_routerF02_db:/data/db
      - mongodb_cluster_routerF02_config:/data/configdb
    ports:
      - 27118:27017
    networks: 
      - shardingf
    restart: always
    links:
      - routerF01

## Config Servers
  configsvrF01:
    image: mongo:5.0.1
    container_name: mongo-config-F01 
    command: mongod --port 27017 --configsvr --replSet rs-config-Fserver
    volumes:
      - ./scripts:/scripts 
      - mongodb_cluster_configsvrF01_db:/data/db
      - mongodb_cluster_configsvrF01_config:/data/configdb
    ports:
      - 27119:27017
    networks: 
      - shardingf
    restart: always
    links:
      - shardF01-a
      - shardF02-a
      - shardF03-a
  configsvrF02:
    image: mongo:5.0.1
    container_name: mongo-config-F02 
    command: mongod --port 27017 --configsvr --replSet rs-config-Fserver
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvrF02_db:/data/db
      - mongodb_cluster_configsvrF02_config:/data/configdb
    ports:
      - 27120:27017
    networks: 
      - shardingf
    restart: always
    links:
      - configsvrF01
  configsvrF03:
    image: mongo:5.0.1
    container_name: mongo-config-F03 
    command: mongod --port 27017 --configsvr --replSet rs-config-Fserver
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvrF03_db:/data/db
      - mongodb_cluster_configsvrF03_config:/data/configdb
    ports:
      - 27121:27017
    networks: 
      - shardingf
    restart: always
    links:
      - configsvrF02

## Shards
  ## Shards 01
   
  shardF01-a:
    image: mongo:5.0.1
    container_name: shard-F01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF01_a_db:/data/db
      - mongodb_cluster_shardF01_a_config:/data/configdb
    ports:
      - 27122:27017
    networks: 
      - shardingf
    restart: always
    links:
      - shardF01-b
      - shardF01-c
  shardF01-b:
    image: mongo:5.0.1
    container_name: shard-F01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF01_b_db:/data/db
      - mongodb_cluster_shardF01_b_config:/data/configdb
    ports:
      - 27123:27017
    networks: 
      - shardingf
    restart: always
  shardF01-c:
    image: mongo:5.0.1
    container_name: shard-F01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF01_c_db:/data/db
      - mongodb_cluster_shardF01_c_config:/data/configdb
    ports:
      - 27124:27017
    networks: 
      - shardingf
    restart: always

  ## Shards 02
  shardF02-a:
    image: mongo:5.0.1
    container_name: shard-F02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF02_a_db:/data/db
      - mongodb_cluster_shardF02_a_config:/data/configdb
    ports:
      - 27125:27017
    networks: 
      - shardingf
    restart: always
    links:
      - shardF02-b
      - shardF02-c
  shardF02-b:
    image: mongo:5.0.1
    container_name: shard-F02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF02_b_db:/data/db
      - mongodb_cluster_shardF02_b_config:/data/configdb
    ports:
      - 27126:27017
    networks: 
      - shardingf
    restart: always
  shardF02-c:
    image: mongo:5.0.1
    container_name: shard-F02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF02_c_db:/data/db
      - mongodb_cluster_shardF02_c_config:/data/configdb
    ports:
      - 27127:27017
    networks: 
      - shardingf
    restart: always

  ## Shards 03
  shardF03-a:
    image: mongo:5.0.1
    container_name: shard-F03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF03_a_db:/data/db
      - mongodb_cluster_shardF03_a_config:/data/configdb
    ports:
      - 27128:27017
    networks: 
      - shardingf
    restart: always
    links:
      - shardF03-b
      - shardF03-c
  shardF03-b:
    image: mongo:5.0.1
    container_name: shard-F03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF03_b_db:/data/db
      - mongodb_cluster_shardF03_b_config:/data/configdb
    ports:
      - 27129:27017
    networks: 
      - shardingf
    restart: always
  shardF03-c:
    image: mongo:5.0.1
    container_name: shard-F03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-F03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shardF03_c_db:/data/db
      - mongodb_cluster_shardF03_c_config:/data/configdb
    ports:
      - 27130:27017
    networks: 
      - shardingf
    restart: always

volumes:
  mongodb_cluster_routerF01_db:
  mongodb_cluster_routerF01_config:
  
  mongodb_cluster_routerF02_db:
  mongodb_cluster_routerF02_config:
  
  mongodb_cluster_configsvrF01_db:
  mongodb_cluster_configsvrF01_config:
  
  mongodb_cluster_configsvrF02_db:
  mongodb_cluster_configsvrF02_config:
  
  mongodb_cluster_configsvrF03_db:
  mongodb_cluster_configsvrF03_config:
  
  mongodb_cluster_shardF01_a_db:
  mongodb_cluster_shardF01_a_config:
  
  mongodb_cluster_shardF01_b_db:
  mongodb_cluster_shardF01_b_config:
  
  mongodb_cluster_shardF01_c_db:
  mongodb_cluster_shardF01_c_config:
  
  mongodb_cluster_shardF02_a_db:
  mongodb_cluster_shardF02_a_config:
  
  mongodb_cluster_shardF02_b_db:
  mongodb_cluster_shardF02_b_config:
  
  mongodb_cluster_shardF02_c_db:
  mongodb_cluster_shardF02_c_config:
  
  mongodb_cluster_shardF03_a_db:
  mongodb_cluster_shardF03_a_config:
  
  mongodb_cluster_shardF03_b_db:
  mongodb_cluster_shardF03_b_config:
  
  mongodb_cluster_shardF03_c_db:
  mongodb_cluster_shardF03_c_config:

networks:
  shardingf: 
      name: shardingf
      external: true
